<?php require_once 'inc'.DIRECTORY_SEPARATOR.'config.php'; ?>
<!DOCTYPE html>
<html lang="pt-br">
  <head>

    <!-- Incluindo head padrão -->
    <?php require_once $head; ?>

  </head>
  <body class="dark muda" id="contBg">
    <!-- Incluindo o menu -->
    <?php require_once $menu; ?>

    <div style="width:100%;height:auto;">

    <img src="<?php echo $conto.'Ariel_1.jpg' ?>" class="" style="width:100%;height:430px;object-fit: cover;object-position: center 30%;"> 

    <div class="container-fluid mt-4  wt-geral  position-relative" style="min-height:81vh;">

        <div class="position-absolute  rounded-pill switch-border" style="right:0;">

        <a id="light" class="m-1" ><?php echo $sun; ?></a>
        <a id="dark" class="m-1" ><?php echo $moon; ?></a>
      
        </div>

        <br>
    
        <center><h1 class="font-antic mt-3 mb-2"> A Pequena Sereia </h1></center>
        <center><h3 class="font-antic mt-3 mb-5"> Hans Christian
Andersen </h3></center>

        <p class="text-justify mb-4 font-s-11 recuo"><span class="font-london font-s-30 mr-2 px-3 border switch-cap text-white muda" style="line-height: 1;">M</span>uito além do oceano, onde a água é tão azul como a flor do loio, e tão clara como o cristal, era um lugar muito, muito profundo, tão profundo, de fato, que nenhum cabo poderia atravessá-lo: muitos campanários de igreja, amontoados uns sobre os outros, não conseguiriam alcançá-lo do chão, abaixo da superfície da água até lá em cima. Lá era o palácio do Rei dos Mares e de seus súditos. Não podemos imaginar que exista algo no fundo do mar mas apenas a areia amarela.</p>
        <div class="row mb-4">

            <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Ariel_5.jpg);width:100%;height:100%;"></div></div>
            <div class="col-12 col-md-8 text-justify font-s-11"> 
              <p class="mb-4 recuo">De fato, as flores e as plantas mais espetaculares crescem nessa região, as folhas e suas hastes são tão flexíveis, que a menor turbulência na água faz com que elas se agitem como se tivessem vida. Peixes, grandes e pequenos, deslizam por entre os galhos, assim como os pássaros voam por entre as árvores aqui na terra. No lugar mais fundo de todos, fica o castelo do Rei dos Mares. Suas muralhas foram construídas com coral, e as janelas longas e no estilo gótico são do mais puro âmbar. O teto é coberto de conchas, que abrem e fecham a medida que as águas fluem sobre elas. A beleza resplandece aqui soberana, pois em cada uma delas há um pérola cintilante, que ficaria perfeita no diadema de uma rainha.</p> 
              <p class="mb-4 recuo"> O Rei dos Mares estava viúvo há muitos anos, e a sua mãe, já idosa, é quem cuidava do palácio para ele. Ela era uma mulher muito sábia, e tinha muito orgulho de sua origem nobre, e por esse motivo ela usava doze ostras na cauda, ao passo que as outras, também com elevada hierarquia, era permitido usar somente seis. Todavia, ela era merecedora de muitos elogios, especialmente pelo cuidado que tinha com as pequenas princesas do mar, as suas netas. Elas eram seis crianças lindas, mas a caçula era a mais bela de todas, sua pele era tão clara e delicada como a pétala de uma rosa, e os seus olhos eram tão azuis como o mar mais profundo, mas, como todas as outras, ela não tinha pés, e o seu corpo terminava numa cauda de peixe.</p>
			  <p class="mb-4 recuo"> O dia todo elas brincavam nos grandes salões do castelo, correndo por entre flores vivas que cresciam ao redor da muralha. As imensas janelas de âmbar eram abertas, e os peixes entravam, assim como as andorinhas voam para dentro de nossas casas quando abrimos as janelas, exceto que os peixes nadavam até as princesas, comiam em suas mãos, e gostavam que fizessem carinho neles. Fora do castelo ficava um belo jardim, onde crescia flores vermelhas e brilhantes e outras azuis escuras, além de inflorescências que pareciam chamas de fogo, as frutas brilhavam que nem ouro, e as folhas e os caules moviam para lá e para cá continuamente. A terra era feito da areia mais delicada, porém, azul como a chama do enxofre incandescente.</p>
            </div>

        </div>

        <div class="row mb-4">

            
          <div class="col-12 col-md-8 text-justify font-s-11"> <p class="mb-4 recuo">Acima de tudo brilhava uma extraordinária radiação azul, como se estivesse rodeada pelo ar lá do alto, através da qual o céu azul brilhava, ao invés das sombrias profundezas do mar. Em tempos de calmaria o sol podia ser visto, parecendo uma flor púrpura, com a luz fluindo do cálice. Cada uma das jovens princesas tinha um pequeno pedaço de terra dentro do jardim, onde elas podiam cavar e plantar o que quisessem. Uma fazia o seu canteiro de flores com o formato de uma baleia, uma outra achou melhor fazer o dela como a figura de uma pequena sereia, mas o canteiro da caçulinha era redondo como sol, e era formado por flores tão vermelhas como os raios do entardecer. Ela era uma criança especial, sossegada e pensativa, e enquanto suas irmãs se regozijavam com as coisas maravilhosas que conseguiam dos naufrágios dos navios, ela não se preocupava com nada, exceto com suas lindas flores vermelhas como o sol, e também de uma maravilhosa estátua de mármore. Ela era a representação de um lindo garoto, esculpida numa pedra totalmente branca, que tinha caído no fundo do mar de algum naufrágio.</p> </div>
          <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Ariel_6.jpg);width:100%;height:100%;"></div></div>
            

        </div>

        <p class="text-justify mb-4 font-s-11 recuo">Ela havia plantado perto da estátuta um pé de chorão de cor rósea. Ele crescia esplendidamente, e em pouco tempo já espalhava seus tenros galhos por cima da estátua, descendo até as areias azuis. A sombra tinha um tom violeta, e ela se movia para lá e para cá como os galhos, parecia como se a coroa da árvore e a raiz estivessem brincando, e tentassem beijar uma a outra. Nada lhe dava tanto prazer como ficar ouvindo sobre as coisas do mar lá em cima. Ela fez com que sua vó lhe contasse tudo o que ela sabia sobre os navios e as cidades, as pessoas e os animais. Para ela não exista coisa mais maravilhosa e mais linda do que saber que as flores da terra tinham perfumes, mas não aquelas que viviam abaixo no mar, e que as árvores das florestas eram verdes, e que os peixes flutuando entre as árvores cantavam com tanta doçura, que era um prazer muito grande ficar ouvindo tudo isso. A sua vó chamava as aves de pequenos peixes, porque a pequenina não entenderia, pois ela nunca tinha visto um pássaro.</p>
        <p class="text-justify mb-4 font-s-11 recuo">- Quando você chegar aos quinze anos, disse a avó, você terá permissão para subir e sair do mar, sentar entre os rochedos ao luar, enquanto os grandes navios ficam passando, e então, você irá conhecer tanto as florestas como as cidades.</p>

        <div class="row mb-4">

            <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_7.jpeg);width:100%;height:100%;background-position: center 70%;"></div></div>
            <div class="col-12 col-md-8 text-justify font-s-11"> 
              <p class="mb-4 recuo">No ano seguinte, uma de suas irmãs completaria quinze anos: mas como cada uma delas era um ano mais jovem que a outra, a mais jovem teria de esperar cinco anos antes de chegar a sua vez para subir até a superfície, para observar a terra como fazemos. No entanto, cada uma prometia dizer às outras o que elas tinham visto na primeira visita, e o que elas tinham achado mais lindo, porque a avó delas não conseguia contar tudo, havia tantas coisas sobre as quais elas queriam ter informação. Nenhuma delas ansiava tanto pela sua vez de subir como a mais jovem, ela que tinha o mais longo tempo de espera, e que era tão sossegada e pensativa. Muitas noites ela ficava perto da janela aberta, olhando através das águas azuis escuras, e admirando os peixinhos chapinhando na água com suas barbatanas e caudas.</p>
              <p class="mb-4 recuo">Ela conseguia ver as estrelas e a lua muito palidamente, mas através da água elas pareciam maiores do que aos nossos olhos. Quando algo como uma nuvem negra passava entre ela e as estrelas, ela sabia que se tratava de alguma baleia nadando acima da sua cabeça, ou um navio cheio de seres humanos, que jamais imaginariam que uma linda sereiazinha estava debaixo deles, acenando com suas mãozinhas brancas para a quilha do navio.</p>
            </div>
        </div>

        <p class="text-justify mb-4 font-s-11 recuo">Assim que a mais velha completou quinze anos, ela teve permissão para subir até a superfície do oceano. Quando voltou, ela tinha centenas de coisas para contar, mas o mais lindo, dizia ela, era ficar sentada ao luar, sobre um banco de areia, no mar tranquilo, perto da costa, e ficar olhando para uma cidade grande que fica ali perto, onde as luzes piscavam como centenas de estrelas, e ficar escutando o som das canções, o barulho das carruagens, e as vozes dos seres humanos, e depois ouvir os sinos tocando e balançando alegremente nos campanários das igrejas, e como ela não podia se aproximar de todas aquelas coisas maravilhosas, ela ficava imaginando como seria tudo aquilo de perto. Oh, e não é que a irmã mais jovem ouvia ansiosa todas essas histórias? e mais tarde, quando ela ficava com a janela aberta olhando através das águas azuis escuras, ela pensava na grande cidade, com todo o barulho e agitação, e até ficava imaginando que ela podia ouvir o som dos sinos tocando, lá embaixo nas profundezas do mar.</p>
		<p class="text-justify mb-4 font-s-11 recuo">No outro ano a segunda irmã recebeu permissão para subir até a superfície da água, e ficar nadando onde ela quisesse. Ela chegou à superfície assim que o sol estava se pondo, e isto, disse ela, era a coisa mais linda que ela já tinha visto. Todo o céu parecia dourado, enquanto nuvens violetas e róseas, que ela não conseguia descrever, flutuavam acima dela, e, ainda mais rápido do que as nuvens, voava um enorme bando de cisnes selvagens em direção ao por do sol, parecendo com um longo véu branco atravessando o mar. Ela também nadou em direção ao sol, mas ele mergulhou no meio das ondas, e as tintas róseas desapareceram das nuvens e do mar.</p>
		<p class="text-justify mb-4 font-s-11 recuo">A vez da terceira irmã havia chegado, ela era a mais corajosa de todas, e ela nadou até um rio muito largo que desembocava no mar. Sentada na margem, ela avistou verdes colinas cobertas com lindos vinhedos, palácios e castelos ficavam espiando por entre as árvores orgulhosas da floresta, ela ouviu os pássaros cantando, e os raios do sol eram tão poderosos que ela muitas vezes era obrigada a mergulhar debaixo das águas para esfriar o rosto que ardia. Numa enseada estreita ela avistou todo um grupo de pequenas crianças humanas, totalmente sem roupas, e que brincavam na água, ela queria brincar com elas, mas elas fugiram muito assustadas, e então, um pequeno animal negro se aproximou da água, era um cachorro, mas ela não sabia disto, porque ela nunca tinha visto um antes. Este animal latiu para ela de modo tão assustador que ela fugiu amedrontada, e correu de volta para o mar aberto. Mas ela disse que jamais se esquecerá da bela floresta, das colinas verdes, e das lindas criancinhas que nadavam na água, embora não tivessem rabo de peixe.</p>
        
		  		  
		  

		<div class="row mb-4">

          <div class="col-12 col-md-8 text-justify font-s-11"> 
		  <p class="mb-4 recuo">A quarta irmã era mais tímida, ela ficou no meio do oceano, mas disse que lá era tudo tão lindo como perto da terra. Ela podia ver há muitas distâncias em torno dela, e o céu lá em cima se parecia como um sino de vidro. Ela tinha visto os navios, mas a uma distância tão grande que eles pareciam como gaivotas. Os golfinhos brincavam com as ondas, e as grandes baleias lançavam água de suas narinas até que pareciam como se centenas de fontes estivessem brincando com água em todas as direções.</p> 
		  <p class="mb-4 recuo">O aniversário da quinta irmã aconteceu no inverno, então, tinha chegado a vez dela, ela viu o que as outras não tinham visto na primeira vez que haviam subido. O mar parecia totalmente verde, e imensos blocos de gelo flutuavam por todos os lados, cada um parecido com uma pérola, disse ela, porém, maiores e mais majestosos do que as igrejas construídas pelos homens. Elas tinham os formatos mais singulares, e brilhavam como diamantes. Ela então, se sentou sobre um dos maiores, e o vento brincava com seus cabelos longos, e ela notou que todos os navios passavam rapidamente, e iam para lugares tão distantes quanto possível dos blocos de gelo, parecia que tinham medo deles. Ao anoitecer, depois que o sol se pôs, nuvens escuras cobriram o céu, os trovões rolavam como pedra e os relâmpagos reluziam, e a luz vermelhava brilhava sobre os blocos de gelo a medida que balançavam e agitavam o mar que subia. Todas as velas dos navios encolhiam de medo e tremiam, enquanto ela se sentava calmamente sobre o iceberg que flutuava, admirando os relâmpagos azuis, quando eles penetravam seus raios com múltiplos braços dentro do mar.</p>
		  
		  </div>
          <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_8.jpg);width:100%;height:100%;"></div></div>
            
        </div>
				
		
		
		<p class="text-justify mb-4 font-s-11 recuo"> Quando as irmãs tiveram permissão para subir à superfície pela primeira vez, todas elas ficaram felizes com as paisagens novas e belas que viram, mas agora, como as garotas já haviam crescido, ela podiam ir para onde quisessem, e até ficaram indiferentes com isso. Elas desejavam voltar novamente para a água, e depois que um mês tinha se passado elas diziam que tudo era muito mais lindo lá embaixo, e que era muito mais agradável ficar em casa. Mas ainda nas horas da noite, as cinco irmãs abraçavam-se umas às outras, e subiam até a superfície, em fileira.</p>
		
		<p class="text-justify mb-4 font-s-11 recuo"> Elas tinham vozes muito mais lindas do que qualquer humano poderia ter, e antes que a tempestade se aproximasse, quando elas pensavam que um navio iria naufragar, elas nadavam diante do barco, e cantavam docemente as delícias que poderiam ser encontradas no fundo do mar, e pediam aos marinheiros para que eles não tivessem medo caso naufragassem até o fundo. Mas os marinheiros não conseguiam entender a canção, e eles pensavam que eram os gritos da tempestade. E elas nunca gostavam de ver estas coisas, pois se o navio afundasse, os homens se afogariam, e apenas o corpo deles chegava ao palácio do Rei dos Mares.</p>
		
		<p class="text-justify mb-4 font-s-11 recuo"> Quando as irmãs subiram, abraçadas umas às outras pelas águas dessa maneira, a irmã mais jovem delas gostava de ficar sozinha, preocupada com elas, pronta para gritar, o único problema era que as sereias não possuíam lágrimas, e por isso elas sofriam mais.<br>- Oh, se eu já tivesse quinze anos, dizia ela: <br>- Eu sei que eu amarei o mundo que fica lá em cima, e todas as pessoas que moram nele. </p>
		
		
			
		
		 <div class="row mb-4">

            <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_10.jpeg);width:100%;height:100%;background-position: center 55%;"></div></div>
            <div class="col-12 col-md-8 text-justify font-s-11"> 
              <p class="mb-4 recuo"> E finalmente ela completou quinze anos. <br>- Bem, agora, você já é adulta, disse a velha viúva, que era sua avó, então, deixe-me enfeitá-la como as suas outras irmãs, e a avó colocou uma coroa de lírios brancos em seus cabelos, e cada pétala da flor era metade de uma pérola. Então, a boa senhora ordenou que oito grandes ostras fossem presas à cauda da princesa a evidenciar sua alta nobreza.</p>
              <p class="mb-4 recuo">- Mas elas me machucam muito, disse a pequena sereia.<br>- A nobreza deve suportar a dor, respondeu a boa senhora. Oh, com alegria ela teria sacudido toda aquela grandeza, e colocado de lado a pesada coroa! As flores vermelhas que cultivava em seu jardim lhe teriam sido muito mais apropriadas, mas de nada adiantava: então, ela disse:<br>- Adeus, e subiu tão leve como uma bolha à superfície da água. O sol já tinha ido dormir quando ela levantou a cabeça acima das ondas, mas as nuvens estavam tingidas de vermelho e dourado, e através do crepúsculo cintilante a estrela da noite brilhava com todo seu esplendor.</p>
		  
		   </div>
        </div>
		<p class="text-justify mb-5 font-s-11 recuo">O mar estava calmo, e a atmosfera estava leve e fresca. Um grande navio, com três mastros, se estendia tranquilo sobre as águas, com apenas uma vela levantada, porque não havia nenhuma brisa, e os marinheiros estavam ociosos no convés enquanto outros retesavam as cordas. Havia canções e musicalidade a bordo, e a medida que a noite se aproximava, centenas de laternas eram acesas, como se as bandeiras de todas as nações tremulassem no ar. A pequena sereia nadou até perto das janelas das cabines, e de vez em quando, quando as ondas a levantavam, ela podia olhar dentro através das janelas transparentes como o vidro, e via dentro um monte de pessoas bem vestidas. Entre elas estava um jovem príncipe, o mais lindo de todos, com olhos negros e arredondados, ele tinha apenas dezesseis anos de idade, e eles estavam comemorando o aniversário dele com muita alegria.</p>
		
		
		<div class="row mb-4">

          <div class="col-12 col-md-8 text-justify font-s-11"> 
		
		<p class="mb-4 recuo">Os marinheiros estavam dançando no convés, mas quando o príncipe saiu para fora da cabine, mais de centenas de foguetes subiram no ar, clareando tudo como se fosse dia. A pequena sereia ficou tão assustada que ela mergulhou para debaixo das águas, e quando ela colocou a cabeça para fora novamente, parecia como se todas as estrelas do céu estivessem caindo ao lado dela, ela nunca tinha visto fogos de artifícios como aqueles antes. Sóis imensos lançavam fogo por toda parte, esplêndidos vagalumes voavam no céu azul, e tudo era refletido no mar calmo lá embaixo. O próprio navio estava tão iluminado que todas as pessoas, e até mesmo a corda mais diminuta, poderia ser vista distinta e claramente. E o jovem príncipe lhe pareceu muito belo, quando ele apertava a mão de todos os presentes e sorria para eles, enquanto a música ecoava através da noite clara.</p>
		<p class="mb-4 recuo">Já era muito tarde, todavia, a pequena sereia não conseguia tirar os olhos do navio, nem do belo príncipe. As lanternas coloridas haviam se apagado, foguetes não subiam mais para o ar, e o canhão havia cessado de atirar, mas o mar ficou inquieto, e um gemido, um som de alguém resmungando podia ser ouvido debaixo das ondas: era uma pequena sereia que havia ficado perto da janeda da cabine, balançando para cima e para baixo sobre a água, o que permitia que ela olhasse dentro. Depois de algum tempo, as velas foram rapidamente desfraldadas, e o navio real prosseguiu a sua viagem, mas logo as ondas subiram mais altas, nuvens pesadas escureciam o céu, e um relâmpago brilhou na distância. Uma tempestade assustadora estava se aproximando, mais uma vez as velas foram enrizadas, e o grande navio prosseguiu em sua rota de viagem sobre o mar furioso.</p>
		<p class="mb-4 recuo">As ondas tinham as alturas das montanhas, e subiam mais altas que o mastro, mas o navio mergulhava como se fosse um cisne entre elas, e depois voltava a subir criando majestosas cristas de espumas. Para a pequena sereia tudo era uma grande alegria, mas não para os marinheiros. De repente o navio rangeu e começou a gemer, as pranchas espessas abriam caminho sob o chicoteamento do mar que estourava em cima do convés, o mastro principal foi reduzido a destroços como se fosse um junco, o navio começou a pender de lado, e a água invadia tudo. A pequena sereia agora percebia que a tripulação corria perigo, até ela mesmo tinha que ter cuidado para evitar as vigas e as tábuas do naufrágio que se espalhavam pela superfície.</p>
		</div>
          <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_11.jpeg);width:100%;height:100%;"></div></div>
            
        </div>
		<p class="text-justify mb-5 font-s-11 recuo">Em determinados momentos a escuridão era tanta que ela não conseguia enxergar um único objeto, mas o clarão de um relâmpago mostrava toda a paisagem, ela podia ver todos que estavam a bordo com exceção do príncipe, quando o navio se rompeu, ela tinha visto quando ele naufragou nas ondas profundas, e ela ficou feliz, porque pensou que ele agora estaria em sua companhia, e então, ela se lembrou que os seres humanos não podiam viver dentro da água, de modo que quando ele descesse até o palácio de seu pai ele já estaria morto.</p>
		
		<div class="row mb-4">

            <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_12.jpeg);width:100%;height:100%;background-position: center 55%;"></div></div>
            <div class="col-12 col-md-8 text-justify font-s-11"> 
		<p class="mb-4 recuo">Mas ele não deveria morrer. Então, ela nadou no meio das vigas e das tábuas que estavam espalhadas pela superfície do mar, esquecendo-se de que elas poderiam esmagá-la em pedacinhos. Então, ela mergulhou profundamente sob as águas escuras, subindo e descendo com o movimento das ondas, até que finalmente ela conseguiu alcançar o jovem príncipe, que rapidamente perdia a força de nadar naquele mar tempestuoso. Seus braços e pernas já não aguentavam mais, seus lindos olhos estavam fechados, e ele teria morrido se a pequena sereia não tivesse vindo ajudá-lo. Ela manteve a cabeça dele fora da água, permitindo que as ondas o levassem para onde quisessem.</p>
		<p class="mb-4 recuo">Pela manhã a tempestade já havia passado, mas do navio nem um único fragmento podia ser visto. O sol subia vermelho e reluzente da água, e seus raios traziam de volta os tons de vitalidade no rosto do príncipe, mas seus olhos permaneciam fechados. A pequena sereia beijou-lhe a testa alta e macia, e ajeitou os seus cabelos úmidos, para ela, ele parecia a estátua de mármore que ela tinha em seu pequeno jardim, e tornou a beijá-lo, e desejava que ele estivesse vivo. De repente a paisagem terrestre se desenhou diante dela, ela via as montanhas azuis e majestosas, sobre as quais a neve branca descansava como se um bando de cisnes tivesse pousado sobre elas. Perto do litoral havia lindas florestas verdes, e nas proximidades ficava um construção alta, porém, ela não conseguia dizer se era uma igreja ou um convento.</p>
		</div>
        </div>
		
		<p class="text-justify mb-5 font-s-11 recuo">Pés de laranja e de limão cresciam no jardim, e na frente das portas estendiam-se majestosas palmeiras. O mar nesse ponto formava uma pequena baía, onde a água era muito calma, porém, muito profunda, então, ela nadou com o belo príncipe até a praia, que era coberta por uma areia fina e branca, e ali ela o depositou sob o calor do sol, tomando o cuidado de levantar a cabeça dele mais alto que o corpo. Os sinos tocavam naquele edifício imenso e branco, e um grupo de garotas vieram até o jardim. A pequena sereia nadou um pouco mais além da praia e ficou sentada entre algumas pedras altas que se elevavam da água, então, ela cobriu a cabeça e o pescoço com a espuma do mar de modo que o seu pequeno rostinho não podia ser visto, e ficou observando para saber o que tinha acontecido com o pobre do príncipe.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Ela não precisou esperar muito até que viu uma garota se aproximar do lugar onde ele havia ficado. A princípio, ela pareceu assustada, mas apenas por alguns momentos, depois foi buscar algumas pessoas, e a pequena sereia viu quando o príncipe voltou à vida novamente, e sorria para aqueles que estavam em volta dele. Mas para ela ele não enviou nenhum sorriso, ele não sabia que ela havia salvo sua vida. Isso fez com que ela ficasse muito triste, e quando ele foi conduzido de volta para o grande edifício, ela mergulhou tristemente para dentro da água, e voltou para o castelo de seu pai. Ela sempre tinha sido silenciosa e meditativa, e agora mais do que nunca. As suas irmãs lhe perguntaram o que ela tinha visto durante a sua primeira visita à superfície da água, mas ela não queria lhes contar nada. Muitas noites e muitas manhãs ela visitou o lugar onde havia deixado o príncipe.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Ela viu quando as frutas do jardim amadureceram até serem colhidas, a neve nos topos das montanhas se derreteram, mas ela nunca voltou a ver o príncipe, e então, ela voltou para casa, cada vez mais triste do que antes. Seu único consolo era ficar sentada em seu pequeno jardim, e colocar seus braços em torno da linda estátua de mármore que se parecia com o príncipe, mas ela deixou de cuidar das flores, e elas cresciam em completa confusão pelos caminhos, entrelaçando suas longas folhas e caules em torno dos galhos das árvores, de modo que o lugar ficou todo escuro e sombrio. Até que ela não aguentou esperar mais, e contou para uma de suas irmãs tudo o que tinha acontecido. Então, as outras ficaram sabendo do segredo, e logo uma amiga da pequena sereia também ficou sabendo e suas amigas íntimas por acaso sabiam quem era o príncipe. Ela também tinha participado da festa no convés do navio, e contou para elas de onde o príncipe era, e onde ficava o seu palácio.</p>
		<p class="text-justify mb-5 font-s-11 recuo">- Venha, minha irmãzinha, disseram as outras princesas, então, elas deram-se os braços e subiram fazendo uma grande fileira até a superfície da água, perto do lugar onde elas sabiam que ficava o palácio do príncipe. Esse lugar era construído com pedras brilhantes amarelas, com longos lances de degraus de mármore, um dos quais descia até o mar. Esplêndidas cúpolas douradas subiam acima do telhado, e entre as colunas que cercavam o edifício todo havia estátuas de mármore que pareciam ter vida. Através dos cristais transparentes das majestosas janelas podiam-se ver os aposentos reais, com cortinas de seda caríssimas e tapetes feitos de tapeçaria, ao passo que as paredes estavam cobertas por pinturas belíssimas proporcionando uma visão muito agradável.</p>
		<p class="text-justify mb-5 font-s-11 recuo">No centro do salão mais amplo uma fonte lançava seus jatos de água cintilantes bem alto até a cúpola de vidro do telhado, através do qual o sol espalhava seus reflexos na água e sobre as lindas plantas que cresciam em torno da base da fonte. Agora que ela sabia onde ele morava, ela passava muitas tardes e muitas noites nas águas perto daquele palácio. Ela gostava de nadar bem perto da praia mais do que as outras se atreviam a fazer isso, e de fato, um dia ela chegou quase perto do canal estreito sob a varanda de mármore, que estendia uma sombra enorme sobre a água. Aqui ela gostava de ficar sentada e olhava o jovem príncipe, que estava totalmente sozinho sob o clarão do luar.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Muitas vezes ele ficava observando quando ele saía para velejar à noite num delicioso barco, com músicas tocando e bandeiras balançando. Ela ficava espiando por entre os juncos verdejantes, e se o vento abraçava seu longo véu branco-prateado, aqueles que observassem de longe acreditariam que ela era um cisne, espraiando suas asas. Durante muitas noites, também, quando os pescadores, com suas tochas, saíam para o mar, ela os ouvia contando tantas coisas bonitas sobre as aventuras do jovem príncipe, que ela ficava feliz por ter salvo a vida dele quando ele foi sacudido quase sem vida no meio das ondas. E ela se lembrava de que a cabeça dele estava deitada em seu peito, e que ela o havia beijado com o coração, mas ele não sabia nada a esse respeito, e não poderia jamais sonhar com ela.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Cada vez mais ela gostava dos seres humanos, e desejava cada vez mais poder passear com aqueles cujo mundo parecia ser muito maior que o dela. Eles podiam viajar pelo mar em navios, e subir as altas colinas que ficavam acima das nuvens, e as terras que eles possuíam, suas florestas e seus campos, se estendiam na distância muito além do alcance dos seus olhos. Havia tanto que ela gostaria de conhecer, e as suas irmãs não conseguiam responder a todas as perguntas que ela fazia. Então, ela procurou a sua avó, que sabia tudo sobre o mundo lá em cima, e que ela, com muita propriedade chamava de terra acima do mar.<br>-Se os seres humanos não se afogarem, perguntou a pequena sereia , eles podem viver para sempre? eles nunca morrem como nós morremos aqui no mar?<br>-Sim, respondeu a gentil senhora, eles também devem morrer, e o tempo de vida deles é mais curto que o nosso. Nós às vezes podemos viver até trezentos anos, mas quando nós deixamos de existir aqui nós viramos apenas espuma na superfície da água, e nós nem sequer temos uma sepultura aqui embaixo daqueles a quem amamos. Não somos almas imortais, jamais viveremos novamente, mas, assim como as algas verdes, uma vez que tenhamos sido cortados, nunca iremos florir novamente. Os seres humanos, pelo contrário, têm uma alma que vive para sempre, sobrevive ao corpo quando este retorna para o pó. Ela ascende através do ar puro e cristalino para além das estrelas reluzentes. Quando nós saímos fora da água, e contemplamos toda a terra do planeta, eles também sobem até regiões desconhecidas e gloriosas que nós jamais veremos.</p>
		<p class="text-justify mb-5 font-s-11 recuo">- Porque nós não temos uma alma imortal? perguntou a pequena sereia com tristeza, Eu daria com alegria todas as centenas de anos que eu tenho para viver, para ser um ser humano apenas por um dia, e para ter a esperança de conhecer a felicidade desse mundo glorioso além das estrelas.<br>- Você não deve pensar assim, disse a boa senhora, nós sentimos que somos muito mais felizes e muito melhores que os seres humanos.<br>- Então, eu morrerei, disse a pequena sereia , e me desfarei como a espuma do mar para nunca mais ouvir a música das ondas, nem admirar as flores maravilhosas nem o sol vermelho. Há algo que possa fazer para conquistar uma alma imortal?<br>-Não, disse a gentil senhora, a não ser que um homem te ame tanto a ponto de você significar mais para ele do que seu pai ou sua mãe, e se todos os pensamentos dele e todo o seu amor forem dedicados a você, e o padre colocar a mão direita dele sobre a sua, e ele prometa fidelidade a você daqui para sempre, então, a alma dele fluirá para o teu corpo e você poderá participar da felicidade futura da humanidade. Ele dará uma alma a você muito embora conservasse a própria, mas isto jamais poderá acontecer. O seu rabo de peixe, que para nós é de beleza singular, na terra é considerado deselegante, eles não conhecem nada melhor, e eles acham que é necessário dois suportes robustos, a que chamam de pernas, para serem considerados belos.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Então, a pequena sereia suspirou, e olhou com tristeza para o seu rabo de peixe.<br>- Sejamos felizes, disse a boa senhora, vamos dançar e pular durante os trezentos anos que temos de viver, isso já é muito tempo, depois disso poderemos descansar para sempre.<br>- Esta noite vamos ter um baile na corte. É um acontecimento fantástico que jamais veremos na terra. As paredes e o teto do imenso salão de baile eram feitos de um cristal espesso, porém, transparente. Centenas de conchas colossais, vestidas de vermelho carmim, e outras verdes como a relva, ficavam enfileiradas uma de cada lado, com uma chama azul interior, iluminando todo o salão, e cujo brilho atravessa as paredes, de modo que o mar fica todo iluminado. Inúmeros peixes, grandes e pequenos, atravessam nadando pelas paredes de cristais, em alguns deles as escamas reluzem com um brilho púrpura, e em outros são cintilantes como a prata e o ouro. Pelos corredores fluía um largo riacho, e nele homens-peixes e sereias dançavam ao som de suas próprias canções.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Ninguém na terra tinha vozes tão lindas como as deles. A pequena sereia cantava, mais do que todos, da maneira mais doce. Toda a corte a aplaudia com suas mãos e suas caudas, e por alguns momentos seu coração pulava de alegria, pois ela sabia que ela tinha a voz mais adorável que qualquer um da terra ou do mar. Mas ela logo voltou a pensar no mundo que ficava acima dela, pois não conseguia esquecer o príncipe encantador, nem a tristeza por não ter uma alma imortal como a dele, então, ela saiu furtiva e silenciosamente do palácio de seu pai, e enquanto tudo lá dentro era alegria e musicalidade, ela se sentou em seu pequeno jardim triste e solitária. Então, ela ouviu o som de uma corneta através da água, e pensou <br>- Certamente ele deve estar velejando lá em cima, aquele a quem meus sonhos pertencem, e em cujas mãos eu gostaria de depositar a felicidade da minha vida. Eu arriscaria tudo por ele, e para conquistar uma alma imortal, enquanto as minhas irmãs estão dançando no palácio do meu pai, irei até a bruxa do mar, de quem sempre tive tanto medo, mas ela poderá me dar conselhos e ajudar.</p>
		<p class="text-justify mb-5 font-s-11 recuo">E então, a pequena sereia saiu de seu jardim, e tomou o caminho até os remoinhos de espuma, onde atrás deles vivia a feiticeira. Ela jamais havia percorrido aqueles caminhos antes: nem flores nem relva cresciam ali, nada além de um terreno estéril, cinzento e arenoso se estendia até o remoinho, onde a água, como rodas de moinho espumejantes, girava em torno de tudo que ela conseguia prender, lançando tudo dentro de um abismo insondável. Pelo meio destes remoinhos destruidores a pequena sereia era obrigada a atravessar, para chegar aos domínios da bruxa do mar, e assim por uma longa distância ela teve de fazer um grande percurso sobre um brejo quente e borbulhante chamado pela bruxa de seu pântano de relvas.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Além destas paragens ficava a casa dela, no meio de uma estranha floresta, na qual todas as árvores e flores eram pólipos, metade animais, metade plantas, elas se pareciam como serpentes com centenas de cabeças se esticando para fora do solo. Os galhos eram longos braços viscosos, com dedos parecidos com vermes flexíveis, movendo um braço após o outro da raiz até o topo. Tudo o que eles conseguiam alcançar no mar eles agarravam, e seguravam com força, de modo que jamais alguém conseguia escapar de suas garras. A pequena sereia ficou tão assustada com o que viu, que ela ficou paralizada, e seu coração batia acelerado, e ela já estava quase pensando em voltar, mas ela se lembrou do príncipe, e na alma humana por quem ela sonhava tanto, e voltou a ter coragem. Ela prendeu seus cabelos longos e lisos em torno da cabeça, para que os pólipos não conseguissem prendê-lo.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Ela juntou as duas mãos sobre o peito, e depois, avançou apressadamente assim como os peixes fazem através da água, entre os braços e dedos flexíveis dos assustadores pólidos, que esticavam seus tentáculos de ambos os lados. Ela percebeu que cada um deles tinha em suas garras algo que eles haviam apreendido com seus numerosos bracinhos, fortes como férreas articulações. Os esqueletos brancos de seres humanos que haviam perecido no mar, e que haviam naufragado em águas profundas, esqueletos de animais terrestres, remos, lemes e baús de navios estavam ali firmemente presos pelos seus tentáculos pegajosos, até mesmo uma pequena sereia, que eles haviam capturado e estrangulado, e esta era a cena mais chocante de todas para a pequena princesa.</p>
		
		<div class="row mb-4">

          <div class="col-12 col-md-8 text-justify font-s-11"> 
		<p class="mb-4 recuo">Ela agora havia chegado a um espaço de terreno pantanoso da floresta, onde serpentes dágua grandes e redondas rolavam na lama, mostrando seus corpos horrendos e assustadores. No meio desse lugar havia uma casa, construída com a ossada dos seres humanos naufragados. Ali ficava a bruxa do mar, que estava brincando com um sapo que comia diretamente de sua boca, assim como as pessoas costumam alimentar um canário com um pouco de açúcar. Ela chamava suas horrendas cobras dágua de queridas galinhas, e deixava que elas ficassem passeando por cima do seu corpo.<br>- Eu sei o que você quer, disse a bruxa do mar, é uma tolice muito grande da sua parte, mas você terá o que deseja, e isso lhe trará muitas aflições, minha linda princesa. Você quer se libertar de sua cauda de peixe, e substituí-la por dois suportes, como os seres humanos da terra, para que o jovem príncipe possa se apaixonar por você, e para que você tenha uma alma imortal." E nesse momento a bruxa gargalhou tão alto e de forma desagradável, que o sapo e as cobras acabaram caindo no chão, e ali permaneceram se contorcendo. Você conseguirá mas no tempo certo, disse a bruxa, pois a partir do por do sol de amanhã eu não poderei te ajudar até que um ano tenha passado. Eu vou te preparar uma poção, com a qual você deverá ir nadando até a terra amanhã antes do por do sol, sentar-se na praia e ali deverá bebê-la.</p>
		</div>
          <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_13.jpg);width:100%;height:100%;"></div></div>
            
        </div>
		
		
        <p class="text-justify mb-5 font-s-11 recuo">A sua cauda então, irá desaparecer, e encolher até aquilo que os homens chamam de pernas, você sentirá muita dor, como se estivesse sendo atravessada por uma espada. Mas todos os que a olharem, dirão que você é a mais linda criaturinha humana que eles já viram. Você manterá ainda a mesma delicadeza de seus movimentos de flutuação, e nenhuma dançarina poderá caminhar com tanta leveza, mas a cada passo teu você sentirá como se estivesse pisando em facas afiadas, e que o sangue precisa fluir. Se você conseguir suportar tudo isto, eu poderei te ajudar.<br>- Sim, vou conseguir, disse a pequena princesa com a voz trêmula, enquanto ela pensava no príncipe e na alma imortal.<br>- Mas pense direito, disse a bruxa,  pois quando o seu corpo assumir a forma de um ser humano, você não poderá mais ser a pequena sereia. Você jamais retornará através da água para junto de suas irmãs, nem para o palácio de teu pai novamente, e se você não conquistar o amor do príncipe, de tal modo que ele esteja disposto a esquecer pai e mãe por tua causa, te amar com toda sua alma, e deixar que o padre junte suas mãos para que vocês se tornem marido e mulher, então, você nunca terá uma alma imortal. Na primeira manhã depois que ele desposar outra mulher o teu coração irá romper, e você se tornará espuma na crista das ondas.<br>- Eu farei isso, disse a pequena sereia, e ela ficou pálida como a morte.<br>- Mas eu também preciso receber o meu pagamento, disse a bruxa, e eu não vou lhe pedir pouco. Você possui a mais bela voz de qualquer um que habite nas profundezas do mar, e você acredita que com ela você conseguirá encantar o príncipe também, mas esta voz será o teu pagamento, a melhor coisa que você possui eu receberei como preço pela minha poção mágica. Meu próprio sangue deve estar misturado com ela, para que a poção possa ser forte como a espada de dois gumes.<br>- Mas se você tomar a minha voz, disse a pequena sereia , o que vai sobrar para mim?<br>- A tua beleza, o teu andar gracioso e os teus olhos expressivos, certamente com estes encantos você saberá acorrentar o coração de um homem. E então, você perdeu a coragem? Coloque a tua língua para fora para que eu possa cortá-la como pagamento, e então você poderá ter o poderoso elixir.<br>- Assim será, disse a pequena sereia.</p>
		
	
		
		<div class="row mb-4">

            <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Ariel_3.jpg);width:100%;height:100%;background-position: center 55%;"></div></div>
            <div class="col-12 col-md-8 text-justify font-s-11"> 
		<p class="mb-4 recuo">Então, a bruxa colocou o seu caldeirão no fogo para preparar a poção mágica.<br>- A higiene é um bom hábito, disse ela, esfregando o caldeirão com as cobras, as quais ela havia amarrado juntas formando um grande nó, em seguida, ela picou a si mesma no peito, e deixou que o sangue escuro escorresse para dentro do caldeirão. O vapor que se levantou transformava-se em figuras de horrível aspecto que ninguém conseguia olhar sem se assustar. A todo momento a bruxa jogava alguma coisa dentro do caldeirão, e quando ele começou a ferver, o ruído se parecia com o choro de um crocodilo. Quando finalmente a poção mágica ficou pronta, ela tinha o aspecto da mais pura água.<br>- Aqui está para você, disse a bruxa. Em seguida, ela cortou a língua da pequena sereia, e então, ela ficou muda, e jamais poderia falar ou cantar. <br>- Se os pólipos tentarem te agarrar quando você estiver voltando pela floresta, disse a bruxa, atire sobre eles algumas gotas da poção, e os dedos deles se rasgarão em milhares de pedaços.<br> Mas a pequena sereia não precisou usar deste artifício, pois os pólipos recuavam aterrorizados quando olhavam para a poção cintilante, que brilhava nas mãos dela como estrelas radiantes.</p>
		</div>
        </div>
        <p class="text-justify mb-5 font-s-11 recuo">Então, ela atravessou rapidamente a floresta e o pantanal, e depois por entre os remoinhos que avançavam. Ela viu que no palácio de seu pai as tochas do salão de baile já haviam sido apagadas, e dentro todos dormiam, mas ela não se arriscou a ir até eles, porque ela agora estava muda e deveria deixá-los para sempre, se sentia como se o seu coração fosse estourar. Ela fugiu sorrateiramente para o jardim, pegou uma flor no canteiro de flores de cada uma de suas irmãs, jogava com a mão milhares de beijos em direção ao palácio, e depois subiu atravessando as águas azuis escuras. O sol nao tinha nascido quando ela surgiu diante do palácio do príncipe, e se aproximou dos maravilhosos degraus de mármore, mas a lua brilhava com muita intensidade.</p>
		
		<div class="row mb-4">

          <div class="col-12 col-md-8 text-justify font-s-11"> 
		
		
		<p class="mb-4 recuo">Então a pequena sereia tomou a poção mágica, e ela sentiu como se uma espada com dois gumes penetrasse o seu corpo delicado: ela sentiu que ia desmaiar, e pareceu que tinha morrido. Quando o sol surgiu e brilhava por todo o oceano, ela voltou a si, e sentiu uma dor aguda, então, bem diante dela estava o belo e jovem príncipe. Ele fixou nela seus olhos negros como carvão tão ardentemente que ela baixou os seus próprios, e então, ela percebeu que o seu rabo de peixe havia desaparecido, e que ela tinha um lindo par de pernas brancas e pés delicados como os de qualquer donzela, mas ela não tinha roupas, então, ela se enrolou em seus cabels longos e espessos. O príncipe perguntou quem ela era, e de onde ela tinha vindo, e ela olhava para ele com ternura e tristeza com seus profundos olhos azuis, mas ela não podia falar.</p>
		<p class="mb-4 recuo">Tudo o que acontecia com ela era exatamente como a bruxa havia dito que seria, ela sentia como se estivesse pisando em pontas de agulhas ou facas afiadas, mas ela suportava tudo com dignidade, e caminhava tão levemente ao lado do príncipe como se fosse bolha de sabão, de modo que ele e todos que a viam ficavam admirados com seus movimentos graciosos e sutis. Não demorou muito e logo ela estava usando roupas caríssimas de seda e musselina, e ela era a mais linda criatura do palácio, mas era muda, e não podia falar nem cantar.</p>
		
		</div>
          <div class="col-12 col-md-4" ><div class="bg-img imgc-size" style="background-image: url(img/cont/Arial_14.jpeg);width:100%;height:100%;"></div></div>
            
        </div>
		
		<p class="text-justify mb-5 font-s-11 recuo">Belas escravas, vestidas em seda e ouro, colocaram-se à frente e cantavam diante do príncipe e dos pais reais: uma cantava melhor que todas as outras, e o príncipe batia palmas e sorria para ela. Esta era uma grande tristeza para a pequena sereia, ela sabia o quanto ela cantava com mais doçura antes, e pensou, <br>- Oh se eu soubesse! Perdi minha voz para sempre, para estar ao lado dele.</p>
		<p class="text-justify mb-5 font-s-11 recuo">As escravas, a seguir, realizaram belos números de dança que pareciam de fada, ao som de uma música maravilhosa. Então, a pequena sereia levantou seus braços encantadores, ficou na ponta dos pés, e deslizava pelo assoalho, e dançava como ninguém ainda havia sido capaz de dançar. A todo momento a sua beleza se revelava cada vez mais, e seus olhos expressivos falavam mais diretamente ao coração do que as canções das escravas. Todos estavam embevecidos, especialmente o príncipe, que a chamava de sua pequena enjeitada, e ela dançava com muita leveza, para agradá-lo, embora cada vez que seus pés tocavam o chão parecia estar pisando em facas afiadas.</p>
		<p class="text-justify mb-5 font-s-11 recuo">O príncipe falou que ela deveria ficar com ele para sempre, e ela teve permissão para dormir junto da sua porta, numa almofada de veludo. Ele mandou fazer para ela uma roupa de escudeiro, para que ela pudesse acompanhá-lo nas cavalgadas. Eles cavalgaram juntos pelas florestas docemente perfumadas, onde os galhos verdes tocavam-lhes os ombros, e os pequenos pássaros cantavam por entre as folhas verdejantes. Ela subiu com o principe até os topos das altas montanhas, e embora seus pés delicados sangrassem a ponto de lhe marcarem os passos, ela ria somente, e o acompanhava até que pudessem ver as nuvens abaixo deles que pareciam um bando de aves migrando para países distantes. Enquanto isso, no palácio do príncipe, quando todos os criados já tinham ido dormir, ela ia e ficava sentada nos largos degraus de mármore, pois isso aliviava os seus pés ardentes, banhando-os na fria água do mar, e então ela pensava em todos aqueles que moravam nas profundezas.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Uma vez, durante a noite, suas irmãs apareceram de braços dados, cantando tristemente, enquanto flutuavam na água. Ela acenou para as irmãs, e então, elas a reconheceram, e disse para elas como ela as havia magoado. Depois disso, elas vinham para o mesmo lugar todas as noites, e uma vez ela viu de longe a sua querida avó, que não vinha à superfície do mar havia muitos anos, e o velho Rei dos Mares, seu pai, com a coroa em sua cabeça. Eles estenderam suas mãos para ela, mas não queriam se arriscar tão perto da terra como suas irmãs faziam.</p>
		<p class="text-justify mb-5 font-s-11 recuo">A medida que os dias se passavam, ela amava o príncipe cada vez mais, e ele a amava como amava a um bebê, mas jamais lhe vinha à cabeça fazer dela a sua esposa, porém, a menos que ela se casasse com ele, ela não receberia uma alma imortal, e, na manhã seguinte depois que o príncipe se casasse com outra mulher, ela iria desaparecer na espuma do mar.<br>- Você não ama a mim mais do que todas elas? os olhos da pequena sereia pareciam perguntar, quando ele a tomou nos braços, e beijou sua linda testa.<br>- Sim, você é muito querida para mim, disse o príncipe, pois você tem o melhor coração, e você é a mais dedicada a mim, você é como uma jovem donzela que eu conheci um dia, mas que eu jamais a verei de novo. Eu estava num navio que havia naufragado, e as ondas me levaram para a praia perto de um templo sagrado, onde várias jovens donzelas executavam o serviço. A mais jovem delas me encontrou na praia, e salvou a minha vida. Eu a vi apenas duas vezes, e ela é a única no mundo a quem devo amar, mas você é muito parecida com ela, e você quase expulsou a imagem dela do meu pensamento. Ela pertence ao templo sagrado, e o meu destino enviou você para mim ao invés dela, e jamais nos separaremos.<br>- Ah, ele não sabe que fui eu quem salvou a vida dele, pensou a pequena sereia . <br> Eu o levei sobre o mar para a floresta onde fica o templo: fiquei sentada debaixo das espumas, e fiquei olhando até que os humanos vieram ajudá-lo. Eu vi a linda jovem que ele ama mais do que ama a mim, e a pequena sereia suspirou profundamente, mas ela não podia verter lágrimas. Ele diz que a jovem pertence ao templo sagrado, portanto, ela jamais voltará para o mundo. Eles nunca mais se encontrarão: ao passo que eu estou aqui ao lado dele, e o vejo todos os dias. Eu cuidarei dele, e o amarei, e renunciarei à minha vida por causa dele.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Não demorou muito e houve um boato de que o príncipe deveria casar, e que a linda filha de um rei vizinho seria a sua esposa, e um lindo navio estava sendo preparado. Embora o príncipe declarasse que ele simplesmente pretendia fazer uma visita ao rei, era de conhecimento geral que ele realmente teria ido fazer uma visita à filha do rei. Um grande séquito o acompanhava. A pequena sereia sorriu, e balançou a cabeça. Ela conhecia os pensamentos do príncipe mais do que qualquer outra pessoa.<br>- Preciso viajar, disse o príncipe a ela, E preciso conhecer esta linda princesa, são os desejos de meus pais, mas eles nao poderão me obrigar a trazê-la para casa como noiva. Não posso amá-la, ela não se parece com a linda donzela do templo, com quem você se parece. Se eu fosse forçado a escolher uma noiva, eu teria escolhido você, minha muda enjeitadinha, com olhos tão expressivos." E então, ele beijou sua boca rosada, brincou com os seus cabelos longos e ondulados, e colocou a cabeça sobre sobre o coração dela, enquanto ela sonhava com a felicidade humana e com uma alma imortal. <br>- Você não tem medo do mar, meu bebê silencioso, disse ele, enquanto estavam no convés do navio real que deveria conduzí-los até o país do rei vizinho. E então ele falou para ela sobre a tempestade e sobre a calmaria, sobre peixes estranhos nas profundezas abaixo de onde eles estavam, e que os mergulhadores tinham visto lá, e ela sorria com as descrições dele, pois ela conhecia mais do que ninguém as maravilhas que haviam no fundo do mar.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Ao luar, quando todos a bordo estavam dormindo, com exceção dos homens no comando, conduzindo o navio, ela se sentou no convés, e ficou olhando através das águas claras. Ela pensou que poderia distinguir o castelo de seu pai, e dentro dele a sua avó já idosa, com a coroa de prata na cabeça, olhando a maré que avançava sob a quilha do navio. De repente, as suas irmãs surgiram no meio das ondas, e ficaram olhando para ela com tristeza, torcendo suas mãos brancas. Ela acenou para suas irmãs, e sorriu, e quis dizer a elas como ela estava feliz e com saúde, mas o grumete se aproximou, e quando suas irmãs voltaram a mergulhar ele pensou ter visto apenas as espumas do mar.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Na manhã seguinte, o navio zarpou para o porto de uma linda cidade que pertencia ao rei a quem o príncipe estava indo visitar. Os sinos da igreja estavam tocando, e das torres majestosas ouvia-se o toque de trombetas, e os soldados, com bandeiras esvoaçantes e baionetas cintilantes, desfilavam pelas rochas por onde passavam. Todo dia era uma festa, bailes e entretenimentos eram realizados um após o outro.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Mas a princesa ainda não havia aparecido. As pessoas diziam que ela cresceu e fora educada numa casa religiosa, onde ela estava aprendendo todas as virtudes reais. Finalmente ela apareceu. Então, a pequena sereia, que estava muito ansiosa para ver se ela era realmente bela, foi constrangida a reconhecer que ela jamais tivera visto antes a mais perfeita imagem da beleza. A sua pele era delicadamente bela, e debaixo de suas pestanas longas e escuras brilhavam seus olhos sorridentes e azuis vestidos de sinceridade e pureza.<br>- Foi você, disse o príncipe, que salvou a minha vida quando eu estava morto na praia, e ele tomou em seus braços a noiva corada. <br>- Oh, eu sou tão feliz, disse ele para a pequena sereia , minhas mais gratas esperanças foram realizadas. Você irá se regozijar com a minha felicidade, porque a sua dedicação a mim é grande e sincera.</p>
		<p class="text-justify mb-5 font-s-11 recuo">A pequena sereia beijou-lhe a mão, e sentiu como se o seu coração já estivesse rompido. A manhã do casamento dele traria a morte para ela, e ela se transformaria na espuma do mar. Todos os sinos da igreja tocaram, e os arautos corriam pela cidade anunciando o noivado. Óleos perfumados queimavam em carissimas lamparinas prateadas de todos os altares. Os sacerdotes balançavam os incensários, enquanto o noivo e a noiva uniam suas mãos e recebiam as bençãos do bispo. A pequena sereia, vestida com seda e ouro, segurava o véu da noiva, mas seus ouvidos nada ouviam das músicas festivas, e os seus olhos não viram nada da cerimônia sagrada, ela pensava na noite da morte que se aproximava, e em tudo o que ela havia perdido no mundo.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Na mesma noite, a noiva e o noivo subiram a bordo do navio, os canhões rufavam, bandeiras tremulavam, e no centro do navio uma tenda caríssima de púrpura e ouro foi erigida. Ela continha sofãs elegantes para a recepção do casal de noivos durante a noite. O navio, com velas infladas e ventos favoráveis, deslizavam com suavidade e leveza sobre o mar calmo. Quando escureceu, um grande número de lâmpadas coloridas foram acesas, e os marinheiros dançavam alegremente pelo convés. A pequena sereia não conseguia parar de pensar na primeira vez que ela subiu até a superfície, e teve festas e alegrias semelhantes, e ela se juntou à dança, se equilibrou no ar como uma andorinha ao perseguir a sua presa, e todos os presentes maravilhados davam vivas. Ela nunca havia dançado com tanta elegância anteriormente.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Seus pés delicados pareciam que eram cortados por facas afiadas, mas ela não se preocupava com isso, uma pontada mais dolorida havia perfurado o seu coração. Ela sabia que esta seria a última noite que veria o príncipe, por quem ela havia abandonado os parentes e a sua casa, ela havia perdido sua linda voz, e sofria diariamente dores inauditas por causa dele, enquanto ele não sabia nada disso. Esta era a última noite que ela iria respirar o mesmo ar com ele, ou olhar para o céu estrelado e o mar profundo, uma noite eterna, sem pensamentos nem sonhos, esperava por ela: ela não tinha uma alma e jamais poderia conseguir uma. Tudo era alegria e felicidade no convés do navio até bem depois da meia-noite, ela ria e dançava com os demais, enquanto os pensamentos da morte varriam-lhe o coração.</p>
		<p class="text-justify mb-5 font-s-11 recuo">O príncipe beijou sua linda noiva, enquanto ela brincava com seus cabelos negros, até que entraram de braços dados para se deitarem na tenda esplêndida. Então, tudo era silêncio à bordo do navio, o timoneiro, sozinho e acordado, ficava no leme. A pequena sereia apoiou seus braços brancos na borda do navio, e olhou para o oriente em busca da primeira paisagem rubra da manhã, porque o primeiro raio da aurora iria lhe trazer a morte. Ela viu suas irmãs subindo por entre as águas: elas estavam tão pálidas quanto ela própria, mas seus cabelos longos e belos não mais balançavam com o vento porque tinham sido cortados.<br>- Nós demos o nosso cabelo para a bruxa, elas disseram, para conseguir ajuda para você, para que você não possa morrer esta noite. Ela nos deu uma faca: aqui está ela, veja como é bastante afiada. Antes do sol nascer você deve mergulhá-la no coração do príncipe, quando o sangue quente cair sobre os seus pés eles se unirão novamente, e se transformarão na cauda de peixe, e você será novamente a pequena sereia, e voltará para nós para viver os seus trezentos anos antes de você morrer e se transformar na espuma do mar salgado. Apresse-se, então, ele ou você deverá morrer antes do por do sol. A nossa velha avó sofre muito por você, que os cabelos brancos dela estão caindo de tanta tristeza, como os nossos foram cortados pela tesoura da bruxa. Mate o príncipe e retorne, vai depressa: você não está vendo os primeiros clarões vermelhos no céu? Em alguns minutos o sol vai nascer, e você deverá morrer. E então elas suspiraram profunda e tristemente, e mergulharam debaixo das ondas.</p>
		<p class="text-justify mb-5 font-s-11 recuo">A pequena sereia afastou a cortina carmesim da tenda, e contemplou a bela noiva com a cabeça deitada no peito do príncipe. Ela se inclinou e beijou sua sobrancelha, em seguida, olhou para o céu onde a aurora rósea ficava cada vez mais brilhante, então, ela olhou para a faca afiada, e novamente fixou os olhos no príncipe, que suspirou o nome da sua noiva em seus sonhos. Ela estava em seus pensamentos, e a faca tremeu na mão da pequena sereia: então ela jogou a faca longe no meio das ondas, e onde ela caiu, a água ficou vermelha, e as gotas que jorravam para cima pareciam sangue.</p>
		<p class="text-justify mb-5 font-s-11 recuo">Ela lançou mais um olhar ansioso e meio-desfalecente para o príncipe, e então, se atirou do navio para o mar, e achou que o seu corpo estava se transformando em espuma. O sol subia por cima das ondas, e seus raios quentes caíam sobre a espuma fria da pequena sereia, que não se sentiu como se estivesse morrendo. Ela viu o sol brilhando, e por todos os lados pairavam centenas de seres belos e translúcidos, ela podia ver através deles as velas brancas do navio, e as nuvens vermelhas do céu, eles falavam melodiosamente, mas era por demais etéreas para serem ouvidos por ouvidos mortais, porque também não poderiam ser vistos por olhos mortais. A pequena sereia percebeu então, que o seu corpo era como o deles, e que ela continuava a subir cada vez mais alto para longe das espumas. <br>- Onde estou eu? perguntou ela, e sua voz parecia sideral, como a voz daqueles que estavam com ela, nenhuma música terreste conseguiria imitá-la.<br>- Entre suas irmãs do espaço, respondeu uma delas. <br>A pequena sereia não possui uma alma imortal, nem pode conseguir uma, exceto se conquistar o amor de um ser humano. No poder de uma outra pessoa está o destino da eternidade. Mas as filhas do espaço, embora não possuam uma alma imortal, podem, com seus atos de bondade, conseguir uma para si mesmas. Nós voamos até os países quentes, e esfriamos o ar abafado que destrói a humanidade com sua pestilência. Nós levamos o perfume das flores para espalhar a saúde e a renovação. Depois de lutarmos por trezentos anos com todo o bem ao nosso alcance, nós recebemos uma alma imortal e tomamos parte da felicidade do mundo. Você, nossa pequena sereia, tentou de todo o coração fazer o que nós estamos fazendo, você sofreu, suportou e se elevou para o mundo espiritual através das suas boas ações, e agora, lutando da mesma maneira durante trezentos anos, você pode conseguir uma alma imortal.</p>
		<p class="text-justify mb-5 font-s-11 recuo">A pequena sereia elevou seus olhos agradecidos em direção ao sol, e sentiu, que pela primeira vez eles estavam cheios de lágrimas. No navio, onde ela havia deixado o príncipe, tudo era vida e burburinho, ela o viu com sua bela noiva e procuravam por ela, com tristeza eles olharam para a espuma perolada, como se eles soubessem que ela havia se atirado nas ondas. Invisível, ela beijou a fronte da sua noiva, e abanou o príncipe, e então subiu com as outras crianças do ar até uma nuvem rósea que flutuava através do éter.</p>
		<p class="text-justify mb-5 font-s-11 recuo">- Depois de trezentos anos, é assim que nos locomovemos no reino dos céus, disse ela. <br>- E nós podemos chegar até lá mais rápido, murmurou uma de suas companheiras. Podemos entrar nas casas das pessoas sem sermos vistas, onde haja crianças, e todos os dias quando encontramos uma boa criança, que é a alegria de seus pais e merecedora do amor deles, o nosso tempo de provação será diminuído. A criança não sabe, quando nós passamos voando pelo ambiente, que nós sorrimos de alegria com o seu bom comportamento, e podemos calcular um ano a menos dos nossos trezentos anos. Mas quando nós observamos uma criança travessa ou mal comportada, nós derramamos lágrimas de tristeza, e para cada lágrima derramada um dia é adicionado ao nosso tempo de provação!</p>
        <center><h1 class="font-antic mt-3 mb-2">Fim</h1></center>
        

    </div>

    </div>

    <br>

    <a href="#top"><?php echo $topo;?></a>

    <!-- incluindo o rodapé -->
    <?php require_once $rodape ?>

    <!-- incluindo scripts -->
    <?php require_once $scriptJs; ?>

  </body>
</html>